/**
 * Mock agent that simulates an AI agent workflow.
 *
 * Demonstrates how a real agent would interact with the sandbox:
 * write files, type check, and build.
 */

import type { Sandbox } from "sandlot";

/**
 * Runs a mock agent that writes a React component and builds it.
 * Returns true if successful, throws on failure.
 */
export async function runMockAgent(sandbox: Sandbox, prompt: string): Promise<void> {
  // Write the component
  const componentCode = generateComponent(prompt);
  await sandbox.fs.writeFile("/src/App.tsx", componentCode);

  // Write entry point
  await sandbox.fs.writeFile("/src/index.tsx", `export { App } from "./App";\nexport { App as default } from "./App";\n`);

  // Type check
  const tscResult = await sandbox.bash.exec("tsc /src/index.tsx");
  if (tscResult.exitCode !== 0) {
    throw new Error(`Type check failed:\n${tscResult.stderr || tscResult.stdout}`);
  }

  // Build
  const buildResult = await sandbox.bash.exec("build /src/index.tsx");
  if (buildResult.exitCode !== 0) {
    throw new Error(`Build failed:\n${buildResult.stderr || buildResult.stdout}`);
  }
}

/**
 * Generate a React component based on the prompt.
 * A real agent would use an LLM here.
 */
function generateComponent(prompt: string): string {
  const lowerPrompt = prompt.toLowerCase();

  if (lowerPrompt.includes("counter")) {
    return `import { useState } from "react";

export function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{ fontFamily: "system-ui", padding: "20px", textAlign: "center" }}>
      <h2>Counter: {count}</h2>
      <div style={{ display: "flex", gap: "10px", justifyContent: "center" }}>
        <button onClick={() => setCount(c => c - 1)}>-</button>
        <button onClick={() => setCount(c => c + 1)}>+</button>
      </div>
    </div>
  );
}
`;
  }

  if (lowerPrompt.includes("time") || lowerPrompt.includes("clock")) {
    return `import { useState, useEffect } from "react";

export function App() {
  const [time, setTime] = useState(new Date());

  useEffect(() => {
    const interval = setInterval(() => setTime(new Date()), 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div style={{ fontFamily: "system-ui", padding: "20px", textAlign: "center" }}>
      <h2>{time.toLocaleTimeString()}</h2>
      <p style={{ color: "#666" }}>{time.toLocaleDateString()}</p>
    </div>
  );
}
`;
  }

  if (lowerPrompt.includes("todo") || lowerPrompt.includes("list")) {
    return `import { useState } from "react";

export function App() {
  const [items, setItems] = useState(["Learn sandlot", "Build something cool"]);
  const [input, setInput] = useState("");

  const addItem = () => {
    if (input.trim()) {
      setItems([...items, input.trim()]);
      setInput("");
    }
  };

  return (
    <div style={{ fontFamily: "system-ui", padding: "20px", maxWidth: "400px" }}>
      <h2>Todo List</h2>
      <div style={{ display: "flex", gap: "8px", marginBottom: "16px" }}>
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && addItem()}
          placeholder="Add a task..."
          style={{ flex: 1, padding: "8px" }}
        />
        <button onClick={addItem}>Add</button>
      </div>
      <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
        {items.map((item, i) => (
          <li key={i} style={{ padding: "8px 0", borderBottom: "1px solid #eee" }}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
`;
  }

  // Default greeting component
  return `export function App() {
  return (
    <div style={{ fontFamily: "system-ui", padding: "20px", textAlign: "center" }}>
      <h2>Hello from the sandbox!</h2>
      <p style={{ color: "#666" }}>Generated by the mock agent</p>
    </div>
  );
}
`;
}
